name: Build & Push Services to ECR

on:
  push:
    branches: [ "main" ]
    paths:
      - "availability-service/**"
      - "order-service/**"
      - "fulfillment-worker/**"

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  ECR_REGISTRY: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ vars.AWS_REGION }}.amazonaws.com

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # -------- Availability Service --------
      - name: Build & Push Availability Service
        if: contains(join(github.event.commits.*.modified, ' '), 'availability-service/')
        run: |
          docker build -t $ECR_REGISTRY/availability-service:latest ./availability-service
          docker push $ECR_REGISTRY/availability-service:latest

      # -------- Order Service --------
      - name: Build & Push Order Service
        if: contains(join(github.event.commits.*.modified, ' '), 'order-service/')
        run: |
          docker build -t $ECR_REGISTRY/order-service:latest ./order-service
          docker push $ECR_REGISTRY/order-service:latest

      # -------- Fulfillment Worker --------
      - name: Build & Push Fulfillment Worker
        if: contains(join(github.event.commits.*.modified, ' '), 'fulfillment-worker/')
        run: |
          docker build -t $ECR_REGISTRY/fulfillment-worker:latest ./fulfillment-worker
          docker push $ECR_REGISTRY/fulfillment-worker:latest
